version: 2.1
orbs:
  slack: circleci/slack@4.3.0
jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm run clean-dist
      - save_cache:
          key: 'modulesAndDist'
          when: on_sucess
          paths:
            - /node_modules
            - /dist
  lint:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: 'modulesAndDist'
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: 'modulesAndDist'
      - run: npm run test
  coverage:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: 'modulesAndDist'
      - run: npm run test:cover
  audit:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - restore_cache:
          key: 'modulesAndDist'
      - run: npm audit
workflows:
  test-and-deploy:
    jobs:
      - build
      - lint:
        - requires:
          - build
      - test:
        - requires:
          - build
      - coverage:
        - requires:
          - build
      - audit:
        - requires:
          - build